### PR TITLE
Return nil when there are no results

### PR DESCRIPTION
**Pull request by singpolyma**
Instead of a broken page with a nil item

### CODE REVIEW

**Comment by ckoegel** [comment]
I'll need to write an explicit test for this before merging. LGTM tho

**Comment by ckoegel** [comment]
Can you send me the request you made to get an empty response list? I'm getting a 404 if the account has no port in orders, and that should be handled differently than if its a 200 with an empty list.

**Comment by singpolyma** [comment]
On an account with port in orders, I asked for the list of orders with status `foc` and got an empty response list

**Comment by ckoegel** [comment]
> On an account with port in orders, I asked for the list of orders with status `foc` and got an empty response list

was that empty response a 200 OK, or a 404 Not Found?

**Comment by singpolyma** [comment]
Was a 200, if it were a 404 the gem would have raised an exception and this code never runs

**Comment by ckoegel** [comment]
> Was a 200, if it were a 404 the gem would have raised an exception and this code never runs

hmmm, that's what should happen, so I'm not sure why I can't get an empty 200. Let me look into this a little more

**Comment by ckoegel** [comment]
Was the status code a 200 or a 204?
Sorry if this seems redundant, we're still trying to replicate and can get a 204, but not an empty 200

**Comment by singpolyma** [comment]
Yes, looks like a 204

**Review by ajrice6713 — APPROVED** [review]

**Review by matthewkmartin — APPROVED** [review]

**Comment by ckoegel** [comment]
Getting released today in v7.0.0
Thanks for the PR!

**Pull request merged**
